fix(FTL-8111): fixed dev environment for Cognito
affinidi/affinidi-core-sdk pull request #278
Opened 2022-12-19 11:09 UTC by oleksiipiliugin

2023-01-21 09:07 UTC, anton-iskryzhytskyi commented on common-libs/common/CHANGELOG.md
> +* # release 2.11.0 (2022-12-07)
```suggestion
# release 2.11.0 (2022-12-07)
```
let's keep our changelog in good state

2023-01-21 09:08 UTC, anton-iskryzhytskyi commented
<img width="443" alt="image" src="https://user-images.githubusercontent.com/36485067/213860221-fb0fe2e7-0d68-40cd-8cf7-ea5c4095d437.png">
what the reason for this amount of changes in pkg-lock?

2023-01-21 09:11 UTC, anton-iskryzhytskyi commented on common-libs/internal-api-clients/src/services/KeyStorageApiService.ts
> +  accessApiKey: string
As I remember, any call to this service require apiKey, so it is not breaking change

2023-01-21 09:12 UTC, anton-iskryzhytskyi commented on sdk/browser/CHANGELOG.md
> +* # release 7.9.0 (2022-12-19)
```suggestion
# release 7.9.0 (2022-12-19)
```

2023-01-21 09:14 UTC, anton-iskryzhytskyi commented on sdk/expo/CHANGELOG.md
> +* # release 7.10.0 (2022-12-19)
```suggestion
# release 7.10.0 (2022-12-19)
```

2023-01-21 09:16 UTC, anton-iskryzhytskyi requested changes
LGTM except some small but important things (including changelogs and pkg-json changes), please check my comments

2023-01-22 16:46 UTC, oleksiipiliugin commented
> <img alt="image" width="443" src="https://user-images.githubusercontent.com/36485067/213860221-fb0fe2e7-0d68-40cd-8cf7-ea5c4095d437.png">
> 
> what the reason for this amount of changes in pkg-lock?

The reason is indentation changes.

2023-01-23 08:01 UTC, yaroslava-kurash approved these changes

2023-01-23 09:18 UTC, anton-iskryzhytskyi approved these changes

2023-01-23 09:34 UTC, merged