feat: [CRF-275] added an option for HolderService to resolve legacy elem locally
affinidi/affinidi-core-sdk pull request #279
Opened 2022-12-19 18:11 UTC by yaroslava-kurash

2022-12-20 08:16 UTC, oleksiipiliugin approved these changes

2022-12-20 08:54 UTC, anton-iskryzhytskyi commented
<img width="397" alt="image" src="https://user-images.githubusercontent.com/36485067/208624969-d2a49c50-c48b-4211-8d68-ca0c1a048b74.png">

2022-12-20 08:59 UTC, anton-iskryzhytskyi requested changes
* Please revise sdk/core/package-lock.json
* add tests

2022-12-22 11:36 UTC, vladmitchenko approved these changes

2022-12-22 11:37 UTC, merged